services:
  intranet:
    build: /opt/intranet
    container_name: intranet
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
        read_only: true

    extra_hosts:
      - "host.docker.internal:host-gateway"
