server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    server_name intranet;
 
    location / {
        add_header Cache-Control "no-store";
 
        allow 192.168.1.0/24;
        allow 10.248.22.0/24;
        allow 10.248.20.0/24;
        allow 10.248.21.0/24;
        allow 10.248.18.0/24;
        allow 10.248.23.0/24;
        allow 10.248.24.0/24;
        allow 10.248.25.0/24;
        deny all;
 
        try_files $uri $uri/ /index.html;
    }
}
 
server {
    listen 80;
    server_name zund;
 
    location / {
        allow 192.168.1.0/24;
        allow 10.248.22.0/24;
        allow 10.248.20.0/24;
        allow 10.248.21.0/24;
        allow 10.248.18.0/24;
        allow 10.248.23.0/24;
        allow 10.248.24.0/24;
        allow 10.248.25.0/24;
        deny all;
 
        proxy_pass http://host.docker.internal:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
